-- 코드를 입력하세요
-- YEAR과 MONTH가 2022, 1인 도서 찾고 
-- SALES CATEGORY별로 합산해서 
-- JOIN해서 정보 가져오기

SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1' 
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;